services:
  web:
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    command: bundle exec foreman start -f ${PROCFILE:-./Procfile.dev}
    # command: tail -f /dev/null
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle
      - ../res:/res
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - db
    environment:
      EDITOR: vi
    user: "${DOCKER_EXEC_USER:-root}"
    labels:
      - dev.orbstack.domains=dt.local
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - .:/app
      - ../res:/res
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    restart: always
    user: root

volumes:
  bundle_data:
  postgres:
