# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://root:root@db/root

test:
  <<: *default
  url: postgres://root:root@db/test

production:
  <<: *default
  database: app_live
  username: app
  password: <%= ENV["DATABASE_PASSWORD"] %>
